source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MFAlertView_Example', :exclusive => true do
  pod 'MFAlertView', :path => '../'
end

target 'MFAlertView_Tests', :exclusive => true do
  pod 'MFAlertView', :path => '../'

  
end
